Adds UI/UX enhancements in different sections of tab layouts
micahflee/onionshare pull request #1176
Opened 2020-09-07 08:24 UTC by SaptakS

Things added:

- Moved the Onion URL address below to take full width
- Increased Size of Title text
- Changed color of title text to purple
- Reduced the size of images in share and website
- Added title to cards in the main tab page
- Reduced size of images
- Adds Onionshare logo in the main page

Fixes #1162 #1163

2020-09-07 22:40 UTC, micahflee requested changes
Nice! So I have a little feedback. Here are screenshots of the 4 modes:

![Screenshot from 2020-09-07 15-22-45](https://user-images.githubusercontent.com/156128/92418851-ac490180-f11e-11ea-99bd-7a316d70db0c.png)
![Screenshot from 2020-09-07 15-22-47](https://user-images.githubusercontent.com/156128/92418853-ace19800-f11e-11ea-9b0d-38ee651c99f6.png)
![Screenshot from 2020-09-07 15-22-50](https://user-images.githubusercontent.com/156128/92418854-ad7a2e80-f11e-11ea-89ec-0d56aaf5b419.png)
![Screenshot from 2020-09-07 15-22-52](https://user-images.githubusercontent.com/156128/92418855-ad7a2e80-f11e-11ea-886c-41e8e6f70d3d.png)

It's nice that share and website mode no longer feel cramped and the URL bar stretches all the way across. But this isn't the case with receive or chat mode.

- [ ] Can you make it so that in all modes the URL bar stretches all the way across at the bottom of the window, and looks consistent?

There is a lot of blank space beneath the history widget (in share and website mode now, but in receive mode too soon). I know that it's because the ServerStatus widget is vertically stacked and has the server button at the top.

- [ ] Could you make it so the history widget stretches all the way down?

I know this might be difficult because it might involve moving the button itself outside of the ServerStatus widget and into a separate widget. But maybe another way of doing it is, when the server is started, you can move the red stop button directly to the right of the URL bar? Sort of like this:

![Screenshot from 2020-09-07 15-36-57](https://user-images.githubusercontent.com/156128/92419097-3d6ca800-f120-11ea-9739-ac25c82febe0.png)

But I don't know I'm open to other suggestions too.

2020-09-08 09:02 UTC, SaptakS commented
Good point. I remember in our discussion @glenn-sorrentino had said to make the history full height in receive mode. So in a way, I missed to do the same for share and website mode. So @micahflee  in that case, the question is, do we want to let the history pane take the entire height in share and website mode also like in receive mode? That removes the issue of blank space and moving button also.

In receive mode also, the URL is much more stretched compared to the current develop one. I also feel, in chat mode, it won't look that good with a single button being in the extrem left bottom. And will look disoriented.

2020-09-09 13:52 UTC, glenn-sorrentino commented
Where’d we land with this? I’d recommend that all of the panels use full height.

On Tue, Sep 8, 2020 at 5:02 AM, Saptak Sengupta <notifications@github.com> wrote:

> Good point. I remember in our discussion [@glenn-sorrentino](https://github.com/glenn-sorrentino) had said to make the history full height in receive mode. So in a way, I missed to do the same for share and website mode. So [@micahflee](https://github.com/micahflee) in that case, the question is, do we want to let the history pane take the entire height in share and website mode also like in receive mode? That removes the issue of blank space and moving button also.
>
> In receive mode also, the URL is much more stretched compared to the current develop one. I also feel, in chat mode, it won't look that good with a single button being in the extrem left bottom. And will look disoriented.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/micahflee/onionshare/pull/1176#issuecomment-688729159), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AGZZDF4GE2EHNCWZEVZCKBTSEXXKVANCNFSM4Q5XOZOQ).

2020-09-14 21:31 UTC, micahflee approved these changes

2020-09-14 21:31 UTC, merged